#!bin/bash
#Creditos
echo -e "\e[1;32mCREDITOS AL CREADOR...!"
echo "Created by: DUANER "
echo "Date: 12/07/2018"
echo "Telegram: NO TENGO PE CAUSHA "
echo "Youtube: TAMPOCO PE "
echo -e "\e[1;33mMensaje: \e[1;36Mno robes mucho\e[0m"
